CREATE TABLE users(
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  email_verified DATETIME NULL,
  image VARCHAR(255) NULL,
  hashed_password VARCHAR(255) NULL,
  user_type ENUM('User','Admin') DEFAULT 'User'
),

ALTER TABLE users
ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN favorite_ids JSON NULL;

CREATE TABLE sessions(
  id VARCHAR(255) PRIMARY KEY,
  session_token VARCHAR(255) UNIQUE NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  expires DATETIME NOT NULL,
  CONSTRAINT fk_session_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
),

CREATE TABLE products(
  id VARCHAR(255) PRIMARY KEY DEFAULT (uuid()),
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  imageSrc VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
)